### ISSUE TITLE
Start a SQL style guide

### ISSUE THREAD

**Issue by harterrt** [mozilla/stmocli#9]

**Comment by mreid-moz** [comment]
- SQL keywords (`UPDATE`, `SELECT`, `AS`, ...) should be uppercase.
- SQL identifiers, including table names and field names, should be lowercase unless quoted*.

*different SQL variants use different quoting mechanisms :(

**Comment by chutten** [comment]
* Presto functions (`COUNT`, `CARDINALITY`, `SUBSTR`) should be uppercase

I'm happy to hear input on chutten style:
```sql
SELECT
    DATE_TRUNC('day', DATE_PARSE(field1, '%Y%m%d')) AS pretty_field1,
    field2 AS pretty_field2,
FROM table_name
WHERE
    field3 IS NOT NULL
    AND (
        field4 IN ('20180301', '20180302')
        OR SUBSTR(field5, 1, 1) = 'a'
    )
GROUP BY 1
```

Notable points I expect contention, and am willing to be swayed, on:
* having `table_name` on the same line as `FROM` (which I defend because there's only one. If there are multiple table names, I would indent like `SELECT` and `WHERE`)
* having `GROUP BY 1` (this is because I don't want to write `GROUP BY DATE_TRUNC('day', DATE_PARSE(field1, '%Y%m%d'))` and have to change it every time I want to see what `'minute'` or `'hour'` might look.)
* Putting `AND` and `OR` at the beginning of lines (I think they'd get lost at the end)
* Where I put my parentheses for nested conditionals (It's essentially the one-true-brace style, but with rounder braces)

**Comment by harterrt** [comment]
+1 to chutten style. Comments:

1. Strongly agree: `table_name` on the same line as `FROM`. I argue that we should prefer explicit `JOIN` statements and shouldn't use multiple table names in a `FROM` statement 
2. I prefer `GROUP BY 1`, but I can see the argument for explicit column names in **reviewed** queries. I think we should allow `GROUP BY 1`
3. Strongly agree with `AND` and `OR` at the beginning of the line. I can't see an argument for end of line. I'm open to allowing rivers in the `WHERE` statement, but my gut says we should outlaw rivers everywhere E.g.:

```sql
WHERE field1 IS NOT NULL
  AND field2 IS > 10
```

4. Strongly agree with parens formatting.

**Comment by mreid-moz** [comment]
- Function names: I somewhat prefer lowercase
- Table names: I prefer "always indented on next line", even if just for one table
- `GROUP BY 1`: strongly agree (though nit in this case it should be `GROUP BY 1, 2` to be valid)
- `AND` and `OR` at the beginning of lines: I agree, but I kind of like the "rivers" alignment approach despised by @harterrt for this case.
- parentheses for nested conditionals: 👍

**Comment by harterrt** [comment]
@mreid-moz - any argument for indenting table names on the next line? I haven't seen this preference before. Does it add to readability? Make queries easier to write?

**Comment by mreid-moz** [comment]
Definitely readability.  You end up with the most important SQL keywords on their own lines which makes it very easy to scan for the logical part you're interested in:
```sql
SELECT
  ... some stuff
FROM
  ... some tables
WHERE
  ... some clauses
GROUP BY
  ... some groupings
HAVING
  ... more clauses
```

**Comment by fbertsch** [comment]
- Function names: We should match the documentation, which is lower case. This is not a strong preference.
- Table names: always _always_ indent on the next line
- Group by: values always go on the next line, e.g.
```
GROUP BY
  field1,
  field2
```
- Require `JOIN` rather than multiple table names

Open question: how to specify the join columns, e.g.
```
FROM
  table1 a
INNER JOIN
  table2 b
  ON a.id = b.a_id
```

**Comment by chutten** [comment]
Having to use a CTE just for sensible `GROUP BY` offends my sense of justice. `GROUP BY` should "just" freakin' take `pretty_field1` as an acceptable identifier.

Also, I contend that CTEs make queries harder to understand, but that might just be me.

**Comment by chutten** [comment]
Seems as though conversation has died out. Shall we omit the controversial subjects (GROUP BY and CTEs) and publish so we don't lose momentum?

I'd like to reference a guide when people contribute SQL examples for docs.tmo

**Comment by harterrt** [comment]
Sounds good to me. @chutten do you have time to take a first pass?

**Comment by harterrt** [comment]
First pass, open for comments:

https://github.com/mozilla/firefox-data-docs/pull/133

**Comment by harterrt** [comment]
:tada: https://docs.telemetry.mozilla.org/concepts/sql_style.html
